# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_meatprice_fixture_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeatOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('meat_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.MeatPrice')),
                ('orderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Orderer')),
            ],
        ),
    ]
