# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_fixture_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderer',
            name='deposit_status',
            field=models.CharField(choices=[('W', 'Waiting'), ('C', 'Complete')], default='W', max_length=1),
        ),
    ]
