# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20170920_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderer',
            name='is_delivery',
            field=models.BooleanField(default=True),
        ),
    ]
